spring:
  application:
      name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gwfeng/configs
          search-paths: respo
          default-label: master
server:
  port: 8888